version: "2"
services:
  web:
    env_file: .env
    build:
      context: .
    command: rails server -p 3000 -b "0.0.0.0"
    environment:
      - APP_NAME=deploymentblocker
    volumes:
      - .:/app
    ports:
      - "80:3000"
    links:
      - mysql

  mysql:
    image: mysql:5.6
    volumes:
      - ~/docker/data/mysql/blinkist_abtester:/var/lib/mysql
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
