version: 2

defaults_deploy: &defaults_deploy
  working_directory: ~/app
  shell: /bin/bash --login
  docker:
    - image: circleci/ruby:2.5.1-node-browsers

jobs:
  specs:
    working_directory: ~/app
    parallelism: 1
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          CIRCLE_CI: true
          RAILS_ENV: test
          MYSQL_URL: "mysql2://root:mysql@127.0.0.1/content_interaction_test"
      - image: circleci/mysql:5.6
        environment:
          MYSQL_DATABASE: content_interaction_test
          MYSQL_ROOT_PASSWORD: mysql

    steps:
      - checkout
      - run: git submodule update --init

      - restore_cache:
          keys:
            - rails-bundle-{{ checksum "Gemfile.lock" }}
            - rails-bundle-
      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --path vendor/bundle

      - save_cache:
          key: rails-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - type: shell
        name: Migrate DB
        command: bundle exec rails db:migrate

      - type: shell
        name: Rspec
        command: |
              bundle exec rspec --profile 10 \
                                --format RspecJunitFormatter \
                                --out test_results/rspec.xml \
                                --format progress \
                                $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: test_results


workflows:
  version: 2
  test_and_build:
    jobs:
      - specs:
          context: Github
