version: 2

defaults_deploy: &defaults_deploy
  working_directory: ~/app
  shell: /bin/bash --login
  docker:
    - image: circleci/ruby:2.5.1-node-browsers

jobs:
  specs:
    working_directory: ~/app
    parallelism: 1
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          CIRCLE_CI: true
          RAILS_ENV: test
          POSTGRES_URL: "postgres://postgres:postgres@127.0.0.1/deployment_blocker_dev"
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: deployment_blocker_dev

    steps:
      - checkout
      - run: git submodule update --init

      - restore_cache:
          keys:
            - rails-bundle-{{ checksum "Gemfile.lock" }}
            - rails-bundle-
      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --path vendor/bundle

      - save_cache:
          key: rails-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m




workflows:
  version: 2
  test_and_build:
    jobs:
      - specs:
          context: Github
